version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@ionic/storage"
    versions:
    - 2.3.1
    - 3.0.2
  - dependency-name: typescript
    versions:
    - 3.9.6
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: ionicons
    versions:
    - 5.4.0
    - 5.5.0
  - dependency-name: cordova-sqlite-storage
    versions:
    - 5.1.0
